# Setup

In [325]:
import numpy as np
import pandas as pd
from tensorflow import keras
from keras import datasets, layers, models
from keras.utils import np_utils
import warnings
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split


warnings.filterwarnings("ignore")


# Prepare the data

In [326]:

# At first we mount the dataset from local file
inputdf = pd.read_csv('Crime.csv')
# sneak peak in the data
inputdf.head(2)

Incident ID Offence Code  CR Number    Dispatch Date / Time NIBRS Code  \
0    201219928         1204  180063894  12/21/2018 09:13:13 PM        120   
1    201301798         5016  200035833  09/13/2020 12:26:58 AM        90Z   

   Victims             Crime Name1         Crime Name2  \
0        1  Crime Against Property             Robbery   
1        1   Crime Against Society  All Other Offenses   

                                  Crime Name3 Police District Name  ...  \
0                        ROBBERY - STREET-GUN              WHEATON  ...   
1  OBSTRUCT GOVT - VIOLATION OF A COURT ORDER           GERMANTOWN  ...   

  Street Prefix Street Name Street Suffix  Street Type  \
0           NaN     GEORGIA           NaN          AVE   
1           NaN    COLTRANE           NaN           DR   

          Start_Date_Time           End_Date_Time  Latitude Longitude  \
0  12/21/2018 09:13:00 PM                     NaN  39.03627  -77.0499   
1  08/08/2020 05:10:00 PM  08/08/2020 12:00:00 AM  39.27784  -77.2115   

  Police District Number             Location  
0                     4D  (39.0363, -77.0499)  
1                     5D  (39.2778, -77.2115)  

[2 rows x 30 columns]

Analyzing the dataset, we observe that columns -


* Incident ID
*	Offence Code
* CR Number
* NIBRS Code
* State (All should be MD)
* Sector, Beat, PRA - meaningless
* Address Number (included in "Block Address")
* Street Prefix (lots of missing values)
* Street Suffix (lots of missing values)
* Police District Number (meaningless)
* Location (pair of Latitude and Longitude)

 are unnecessary. So they are removed.

In [327]:
# dropping the unnecessary columns
#inputdf = data
unnecessary_columns = ['Incident ID', 'Offence Code', 'CR Number', 'NIBRS Code', 'State', 'Sector', 'Beat', 'PRA', 'Address Number', 'Street Prefix', 'Street Suffix', 'Police District Number', 'Location'  ]
for i in unnecessary_columns:
  inputdf = inputdf.drop(i, axis=1)
inputdf.head(2)

Dispatch Date / Time  Victims             Crime Name1  \
0  12/21/2018 09:13:13 PM        1  Crime Against Property   
1  09/13/2020 12:26:58 AM        1   Crime Against Society   

          Crime Name2                                 Crime Name3  \
0             Robbery                        ROBBERY - STREET-GUN   
1  All Other Offenses  OBSTRUCT GOVT - VIOLATION OF A COURT ORDER   

  Police District Name           Block Address           City  Zip Code  \
0              WHEATON  11100 BLK  GEORGIA AVE  SILVER SPRING   20902.0   
1           GERMANTOWN  25600 BLK  COLTRANE DR       DAMASCUS   20872.0   

  Agency                      Place Street Name Street Type  \
0   MCPD          Street - Bus Stop     GEORGIA         AVE   
1   MCPD  Parking Lot - Residential    COLTRANE          DR   

          Start_Date_Time           End_Date_Time  Latitude  Longitude  
0  12/21/2018 09:13:00 PM                     NaN  39.03627   -77.0499  
1  08/08/2020 05:10:00 PM  08/08/2020 12:00:00 AM  39.27784   -77.2115

# Later, Columns related with the effect of crime are removed.

In [328]:
unnecessary_columns = ['Dispatch Date / Time', 'Victims', 'Block Address', 'Street Type', 'Agency', 'End_Date_Time']
for i in unnecessary_columns:
  inputdf = inputdf.drop(i, axis=1)
inputdf.head(2)

Crime Name1         Crime Name2  \
0  Crime Against Property             Robbery   
1   Crime Against Society  All Other Offenses   

                                  Crime Name3 Police District Name  \
0                        ROBBERY - STREET-GUN              WHEATON   
1  OBSTRUCT GOVT - VIOLATION OF A COURT ORDER           GERMANTOWN   

            City  Zip Code                      Place Street Name  \
0  SILVER SPRING   20902.0          Street - Bus Stop     GEORGIA   
1       DAMASCUS   20872.0  Parking Lot - Residential    COLTRANE   

          Start_Date_Time  Latitude  Longitude  
0  12/21/2018 09:13:00 PM  39.03627   -77.0499  
1  08/08/2020 05:10:00 PM  39.27784   -77.2115

Some columns are confusing to be added now. Such as -

* Crime Name3
* Also we have to take special care of Latitude and Longitude if we want them to include in our feature set.

# Drop rows from the dataframe based on certain condition applied on a column


In [329]:
# Filter all rows for Latitude is greater than or equal to 35
inputdf = inputdf[inputdf['Latitude'] > 35.0]
# inputdf['Latitude'].hist()
# Filter all rows for Longitude is less than or equal to -70
inputdf = inputdf[inputdf['Longitude'] < -70]
# inputdf['Longitude'].hist()



# inputdf['Crime Name2'].value_counts()
# # Filter all rows for that has occurances less than 5
# inputdf = inputdf[inputdf.columns[inputdf['Crime Name2'].value_counts() > 5]]

# Creating The Location Based Crime Data Frame

In [330]:
# loc_crime_df = inputdf[['Latitude', 'Longitude', 'Crime Name1']]
loc_crime_df = inputdf[['Crime Name1','Crime Name2', 'Police District Name', 'City', 'Zip Code', 'Place', 'Street Name', 'Latitude', 'Longitude']]
dates = pd.to_datetime(inputdf['Start_Date_Time'])
  
# extract Hours from Timestamp 
# rs = dates.dt.hour
# print(rs)
loc_crime_df['dateHour'] = dates.dt.hour
loc_crime_df['day'] = dates.dt.day
loc_crime_df['month'] = dates.dt.month
loc_crime_df.head()
# print(loc_crime_df.shape)
# loc_crime_df.dtypes


Crime Name1                  Crime Name2 Police District Name  \
0  Crime Against Property                      Robbery              WHEATON   
1   Crime Against Society           All Other Offenses           GERMANTOWN   
2   Crime Against Society  Driving Under the Influence            ROCKVILLE   
3                   Other           All Other Offenses            ROCKVILLE   
4  Crime Against Property                  Shoplifting           GERMANTOWN   

            City  Zip Code                               Place Street Name  \
0  SILVER SPRING   20902.0                   Street - Bus Stop     GEORGIA   
1       DAMASCUS   20872.0           Parking Lot - Residential    COLTRANE   
2      ROCKVILLE   20850.0                 Street - In vehicle     GRANDIN   
3      ROCKVILLE   20850.0                      Street - Other     GRANDIN   
4     GERMANTOWN   20876.0  Retail - Department/Discount Store   FREDERICK   

    Latitude  Longitude  dateHour  day  month  
0  39.036270 -77.049900        21   21     12  
1  39.277840 -77.211500        17    8      8  
2  39.086688 -77.144754         2    3      1  
3  39.086688 -77.144754         2    3      1  
4  39.198295 -77.244900        17   16      7

In [331]:
# Removing Rows on Count condition
counts = loc_crime_df['Crime Name2'].value_counts()
# print(counts)
threshold = 100
loc_crime_df = loc_crime_df.loc[loc_crime_df['Crime Name2'].isin(counts.index[counts >= threshold ])]

In [332]:
# Removing Rows on Count condition 
# Pruning garbage data
# loc_crime_df = loc_crime_df[~loc_crime_df['Crime Name2'] == "All Other Offenses"]
indexAge = loc_crime_df[ loc_crime_df['Crime Name2'] == "All Other Offenses" ].index
loc_crime_df.drop(indexAge , inplace=True)
loc_crime_df.head()
counts = loc_crime_df['Crime Name2'].value_counts()
# print(counts)


# Taking only Top n classes in a column


In [333]:
target_column = 'Crime Name1'
top_n = 2
top_classes_dict = {}
top_classes_dict = loc_crime_df[target_column].value_counts().nlargest(top_n).to_dict()
top_classes_series = loc_crime_df[target_column].value_counts().nlargest(top_n)
print(top_classes_series)
print('Dictionary is + '+str(top_classes_dict))
str_array = []
temp_df = pd.DataFrame()
for x in top_classes_dict.keys():
    str_array.append(x)
    rows = loc_crime_df[loc_crime_df[target_column] == str (x) ]
    # print(rows)
    temp_df = temp_df.append(rows)
# print(str_array)
# temp_df

Crime Against Property    140065
Crime Against Society      57349
Name: Crime Name1, dtype: int64
Dictionary is + {'Crime Against Property': 140065, 'Crime Against Society': 57349}


In [334]:
loc_crime_df = temp_df
print(loc_crime_df[target_column].value_counts())

Crime Against Property    140065
Crime Against Society      57349
Name: Crime Name1, dtype: int64


# Dropping null values in Zip code

In [335]:
loc_crime_df['Zip Code'].value_counts()
# loc_crime_df['dateHour'].value_counts()
loc_crime_df = loc_crime_df.dropna(axis=0, subset=['Zip Code'])
print(loc_crime_df.shape)

(195178, 12)


In [336]:
loc_crime_df.head()

Crime Name1                     Crime Name2  \
0   Crime Against Property                         Robbery   
4   Crime Against Property                     Shoplifting   
10  Crime Against Property  Burglary/Breaking and Entering   
13  Crime Against Property                     Shoplifting   
17  Crime Against Property                     Shoplifting   

   Police District Name           City  Zip Code  \
0               WHEATON  SILVER SPRING   20902.0   
4            GERMANTOWN     GERMANTOWN   20876.0   
10             BETHESDA       BETHESDA   20816.0   
13             BETHESDA       BETHESDA   20817.0   
17            ROCKVILLE      ROCKVILLE   20850.0   

                                 Place Street Name   Latitude  Longitude  \
0                    Street - Bus Stop     GEORGIA  39.036270 -77.049900   
4   Retail - Department/Discount Store   FREDERICK  39.198295 -77.244900   
10        Retail - Drug Store/Pharmacy  MAC ARTHUR  38.965620 -77.139000   
13                       Retail - Mall   DEMOCRACY  39.022077 -77.147376   
17  Retail - Department/Discount Store  HUNGERFORD  39.092059 -77.153305   

    dateHour  day  month  
0         21   21     12  
4         17   16      7  
10         3   21      8  
13        16    7      2  
17        18   10      9

# Transform the data by label encoding

In [337]:
# encode class values as integers
encoder = LabelEncoder()
encoded_Y = encoder.fit_transform( loc_crime_df[target_column])
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
print(dummy_y)


[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [338]:
print(dummy_y.shape)

(195178, 2)


In [339]:
encoded_dict ={}
temp_df_2 = pd.DataFrame()

def label_encoder(y):
    le = LabelEncoder()
    if str(y) == target_column:
        print(loc_crime_df[y])
    loc_crime_df[y] = le.fit_transform(loc_crime_df[y])
    if str(y) == target_column:
        print(loc_crime_df[y])
    if str(y) == target_column:
        temp_df_2[y] = le.inverse_transform(loc_crime_df[y])
        # encoded_dict = {loc_crime_df[y], temp_df_2[y]} 
    #print(temp_df[y])

#loc_crime_df = inputdf[['Crime Name1','Crime Name2', 'Police District Name', 'City', 'Place', 'Street Name']]

label_list = ['Crime Name2', 'Police District Name', 'City', 'Place', 'Street Name']


# label_list = ['Crime Name1','Crime Name2', 'Police District Name', 'City', 'Place', 'Street Name']
#label_list = ['Crime Name1']

for l in label_list:
    label_encoder(l)

# print(encoded_dict)
 
#Display transformed data
loc_crime_df.head()
print(loc_crime_df.shape)

(195178, 12)


In [340]:
# Going for specigic prediction without geolocation
# X = loc_crime_df.drop([target_column],axis=1)
# y = loc_crime_df[target_column]

# Going for specigic prediction without geolocation
# X = loc_crime_df.drop([target_column, 'Latitude', 'Longitude'],axis=1)
# y = loc_crime_df[target_column]


# Going for generic prediction
X = loc_crime_df.drop([target_column,'Crime Name2', 'Latitude', 'Longitude'],axis=1)
# y = loc_crime_df[[target_column, 'Latitude', 'Longitude']]


# print(X)
X.shape

(195178, 8)

In [341]:
# Dropping a Pandas Index Column Using reset_index so that it doesn't have conflict with the second dataframe
df1 =loc_crime_df[['Latitude', 'Longitude']]
df1 = df1.reset_index(drop=True)
print(df1.shape)
df1.head()

(195178, 2)


Latitude  Longitude
0  39.036270 -77.049900
1  39.198295 -77.244900
2  38.965620 -77.139000
3  39.022077 -77.147376
4  39.092059 -77.153305

In [342]:
df2=pd.DataFrame(dummy_y, columns = [x for x in str_array])
print(df2.shape)

df2.head()

(195178, 2)


Crime Against Property  Crime Against Society
0                     1.0                    0.0
1                     1.0                    0.0
2                     1.0                    0.0
3                     1.0                    0.0
4                     1.0                    0.0

In [343]:
# concatenate a mix of Series and DataFrame objects
y = pd.concat([df1, df2], axis = 1)
y.shape
print(y)

         Latitude  Longitude  Crime Against Property  Crime Against Society
0       39.036270 -77.049900                     1.0                    0.0
1       39.198295 -77.244900                     1.0                    0.0
2       38.965620 -77.139000                     1.0                    0.0
3       39.022077 -77.147376                     1.0                    0.0
4       39.092059 -77.153305                     1.0                    0.0
...           ...        ...                     ...                    ...
195173  39.144990 -77.205500                     0.0                    1.0
195174  39.180560 -77.243900                     0.0                    1.0
195175  39.246760 -77.191000                     0.0                    1.0
195176  39.061240 -77.051200                     0.0                    1.0
195177  38.989630 -76.992300                     0.0                    1.0

[195178 rows x 4 columns]


In [344]:
# y = pd.concat([loc_crime_df[['Latitude', 'Longitude']], pd.DataFrame(dummy_y, columns = ['Y1', 'Y2'])], axis = 1, ignore_index= True)

# Split the data into training and testing set


In [345]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,
                                               random_state=42, shuffle = True) 

#Data was splitted as 80% train data and 20% test data.

# y_train = y_train.values.reshape(-1,1)
# y_test = y_test.values.reshape(-1,1)

print("X_train shape:",X_train.shape)
print("X_test shape:",X_test.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

X_train shape: (156142, 8)
X_test shape: (39036, 8)
y_train shape: (156142, 4)
y_test shape: (39036, 4)


In [348]:
# Feature Scaling (Standardize the data)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
y_train = sc.fit_transform(y_train)
y_test = sc.transform(y_test)

In [349]:
print(y_train)

[[-0.37842894 -0.55862732  0.63768853 -0.63768853]
 [-1.12145973  0.85317159 -1.56816368  1.56816368]
 [ 0.89978456 -0.96452213  0.63768853 -0.63768853]
 ...
 [ 0.15728175  0.46560922  0.63768853 -0.63768853]
 [-0.80021367  1.41630615 -1.56816368  1.56816368]
 [ 1.68203848 -1.41156197  0.63768853 -0.63768853]]


In [347]:

# Md Hasan Shahriar
# Tue, Dec 6, 6:51 PM 


feature_number = 8
output_dim = 1+2


model = keras.Sequential(
    [
        keras.Input(shape=feature_number),
        layers.Dense(100, activation="relu"),
        layers.Dense(50, activation="relu"),
        layers.Dense(output_dim, activation="softmax"),
    ]
)

model.summary()


batch_size = 128
epochs = 15

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 100)               900       
                                                                 
 dense_25 (Dense)            (None, 50)                5050      
                                                                 
 dense_26 (Dense)            (None, 3)                 153       
                                                                 
Total params: 6,103
Trainable params: 6,103
Non-trainable params: 0
_________________________________________________________________
Epoch 1/15


ValueError: in user code:

    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\training.py", line 1024, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\training.py", line 1082, in compute_loss
        return self.compiled_loss(
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\losses.py", line 284, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\losses.py", line 2004, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "e:\Crime Prediction for Montgomer County\Crime-Prediction-for-Montgomery-County\venv-crime\lib\site-packages\keras\backend.py", line 5532, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 4) and (None, 3) are incompatible


In [ ]:
history.history['val_loss']

# Evaluate the trained model


In [ ]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

In [ ]:
# # Model / data parameters
# num_classes = 10
# input_shape = (28, 28, 1)



# # Load the data and split it between train and test sets
# (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# # Scale images to the [0, 1] range
# x_train = x_train.astype("float32") / 255
# x_test = x_test.astype("float32") / 255
# # Make sure images have shape (28, 28, 1)
# x_train = np.expand_dims(x_train, -1)
# x_test = np.expand_dims(x_test, -1)
# print("x_train shape:", x_train.shape)
# print(x_train.shape[0], "train samples")
# print(x_test.shape[0], "test samples")


# # convert class vectors to binary class matrices
# y_train = keras.utils.to_categorical(y_train, num_classes)
# y_test = keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(inputdf.shape)
# 'column names are:' 
inputdf.columns
inputdf.dtypes

# Build the model


In [ ]:
model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ]
)

model.summary()

# Train the model


In [ ]:
batch_size = 128
epochs = 15

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)